In [8]:
import pandas as pd

In [9]:
df = pd.read_csv('FMCG Sales Dataset.csv')
df.head()

,Invoice_ID,Invoice_Date,City,Store_Format,Category,Brand,Channel,Payment_Mode,Units,Cost_Price,...,Revenue,Cost,Margin,Margin_%,Stock_On_Hand,Reorder_Level,Lead_Time_Days,Customer_Age,Customer_Gender,Loyalty_Flag
0,58018430,02-02-2024 13:50,Kolkata,Super,Grocery,Nestle,Online,Wallet,2,148.999035,...,350.114418,297.998070,52.116348,0.148855,154,31,11,20.0,M,1
1,48157952,09-10-2024 11:52,Hyderabad,Hyper,Home Care,PepsiCo,Offline,Wallet,1,80.626759,...,106.034197,80.626759,25.407438,0.239616,130,24,5,26.0,F,1
2,23283831,26-08-2024 22:03,Chennai,Hyper,Snacks,PepsiCo,Online,Card,5,181.233170,...,1044.900114,906.165848,138.734266,0.132773,270,44,8,27.0,F,0
3,53537460,09-06-2024 04:34,Bengaluru,Hyper,Beverages,Nestle,Omnichannel,Card,2,195.811403,...,521.759920,391.622805,130.137115,0.249420,403,63,8,NaN,F,0
4,55348596,07-06-2024 01:13,Delhi,Super,Snacks,ITC,Offline,Card,3,23.571888,...,91.873416,70.715665,21.157751,0.230292,366,40,9,60.0,F,1

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 21 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   Invoice_ID       100000 non-null  int64
 1   Invoice_Date     100000 non-null  object
 2   City             100000 non-null  object
 3   Store_Format     100000 non-null  object
 4   Category         100000 non-null  object
 5   Brand            100000 non-null  object
 6   Channel          100000 non-null  object
 7   Payment_Mode     100000 non-null  object
 8   Units            100000 non-null  int64
 9   Cost_Price       100000 non-null  float64
 10  Selling_Price    100000 non-null  float64
 11  Revenue          100000 non-null  float64
 12  Cost             100000 non-null  float64
 13  Margin           100000 non-null  float64
 14  Margin_%         100000 non-null  float64
 15  Stock_On_Hand    100000 non-null  int64
 16  Reorder_Level    100000 non-null  int64
 17  Lead_Time_Days   100000 non-null  int64
 18  Customer_Age     59919 non-null   float64
 19  Customer_Gender  94952 non-null   object
 20  Loyalty_Flag     100000 non-null  int64
dtypes: float64(7), int64(6), object(8)
memory usage: 16.0+ MB

In [11]:
df.isnull().sum()

Invoice_ID             0
Invoice_Date           0
City                   0
Store_Format           0
Category               0
Brand                  0
Channel                0
Payment_Mode           0
Units                  0
Cost_Price             0
Selling_Price          0
Revenue                0
Cost                   0
Margin                 0
Margin_%               0
Stock_On_Hand          0
Reorder_Level          0
Lead_Time_Days         0
Customer_Age       40081
Customer_Gender     5048
Loyalty_Flag           0
dtype: int64

In [12]:
df

,Invoice_ID,Invoice_Date,City,Store_Format,Category,Brand,Channel,Payment_Mode,Units,Cost_Price,...,Revenue,Cost,Margin,Margin_%,Stock_On_Hand,Reorder_Level,Lead_Time_Days,Customer_Age,Customer_Gender,Loyalty_Flag
0,58018430,02-02-2024 13:50,Kolkata,Super,Grocery,Nestle,Online,Wallet,2,148.999035,...,350.114418,297.998070,52.116348,0.148855,154,31,11,20.0,M,1
1,48157952,09-10-2024 11:52,Hyderabad,Hyper,Home Care,PepsiCo,Offline,Wallet,1,80.626759,...,106.034197,80.626759,25.407438,0.239616,130,24,5,26.0,F,1
2,23283831,26-08-2024 22:03,Chennai,Hyper,Snacks,PepsiCo,Online,Card,5,181.233170,...,1044.900114,906.165848,138.734266,0.132773,270,44,8,27.0,F,0
3,53537460,09-06-2024 04:34,Bengaluru,Hyper,Beverages,Nestle,Omnichannel,Card,2,195.811403,...,521.759920,391.622805,130.137115,0.249420,403,63,8,NaN,F,0
4,55348596,07-06-2024 01:13,Delhi,Super,Snacks,ITC,Offline,Card,3,23.571888,...,91.873416,70.715665,21.157751,0.230292,366,40,9,60.0,F,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,51439182,11-08-2024 14:58,Mumbai,Express,Dairy,Britannia,Online,Cash,5,128.336814,...,868.639139,641.684070,226.955069,0.261277,70,76,6,25.0,NaN,0
99996,76433622,27-11-2024 11:02,Ahmedabad,Express,Dairy,Amul,Offline,Wallet,4,183.100266,...,961.820263,732.401065,229.419198,0.238526,482,31,14,25.0,M,1
99997,80228351,21-02-2024 09:25,Bengaluru,Express,Beverages,ITC,Omnichannel,Wallet,2,163.630389,...,349.940290,327.260777,22.679513,0.064810,411,40,4,NaN,F,0
99998,49574701,30-03-2024 04:11,Chennai,Hyper,Dairy,PepsiCo,Offline,UPI,4,50.230907,...,270.132573,200.923627,69.208946,0.256204,488,46,12,21.0,M,1
99999,17631041,11-07-2024 08:42,Pune,Super,Snacks,ITC,Offline,UPI,2,14.754033,...,38.174656,29.508066,8.666590,0.227025,211,22,9,26.0,M,0

In [ ]:
# Convert Invoice_Date Column

df['Invoice_Date'] = pd.to_datetime(df['Invoice_Date'], 
                                    format = '%d-%m-%Y %H:%M')
df

,Invoice_ID,Invoice_Date,City,Store_Format,Category,Brand,Channel,Payment_Mode,Units,Cost_Price,...,Revenue,Cost,Margin,Margin_%,Stock_On_Hand,Reorder_Level,Lead_Time_Days,Customer_Age,Customer_Gender,Loyalty_Flag
0,58018430,2024-02-02 13:50:00,Kolkata,Super,Grocery,Nestle,Online,Wallet,2,148.999035,...,350.114418,297.998070,52.116348,0.148855,154,31,11,20.0,M,1
1,48157952,2024-10-09 11:52:00,Hyderabad,Hyper,Home Care,PepsiCo,Offline,Wallet,1,80.626759,...,106.034197,80.626759,25.407438,0.239616,130,24,5,26.0,F,1
2,23283831,2024-08-26 22:03:00,Chennai,Hyper,Snacks,PepsiCo,Online,Card,5,181.233170,...,1044.900114,906.165848,138.734266,0.132773,270,44,8,27.0,F,0
3,53537460,2024-06-09 04:34:00,Bengaluru,Hyper,Beverages,Nestle,Omnichannel,Card,2,195.811403,...,521.759920,391.622805,130.137115,0.249420,403,63,8,NaN,F,0
4,55348596,2024-06-07 01:13:00,Delhi,Super,Snacks,ITC,Offline,Card,3,23.571888,...,91.873416,70.715665,21.157751,0.230292,366,40,9,60.0,F,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,51439182,2024-08-11 14:58:00,Mumbai,Express,Dairy,Britannia,Online,Cash,5,128.336814,...,868.639139,641.684070,226.955069,0.261277,70,76,6,25.0,NaN,0
99996,76433622,2024-11-27 11:02:00,Ahmedabad,Express,Dairy,Amul,Offline,Wallet,4,183.100266,...,961.820263,732.401065,229.419198,0.238526,482,31,14,25.0,M,1
99997,80228351,2024-02-21 09:25:00,Bengaluru,Express,Beverages,ITC,Omnichannel,Wallet,2,163.630389,...,349.940290,327.260777,22.679513,0.064810,411,40,4,NaN,F,0
99998,49574701,2024-03-30 04:11:00,Chennai,Hyper,Dairy,PepsiCo,Offline,UPI,4,50.230907,...,270.132573,200.923627,69.208946,0.256204,488,46,12,21.0,M,1
99999,17631041,2024-07-11 08:42:00,Pune,Super,Snacks,ITC,Offline,UPI,2,14.754033,...,38.174656,29.508066,8.666590,0.227025,211,22,9,26.0,M,0

In [14]:
# Additional Column

df['Month'] = df['Invoice_Date'].dt.month_name()
df['Day'] = df['Invoice_Date'].dt.day_name()
df

,Invoice_ID,Invoice_Date,City,Store_Format,Category,Brand,Channel,Payment_Mode,Units,Cost_Price,...,Margin,Margin_%,Stock_On_Hand,Reorder_Level,Lead_Time_Days,Customer_Age,Customer_Gender,Loyalty_Flag,Month,Day
0,58018430,2024-02-02 13:50:00,Kolkata,Super,Grocery,Nestle,Online,Wallet,2,148.999035,...,52.116348,0.148855,154,31,11,20.0,M,1,February,Friday
1,48157952,2024-10-09 11:52:00,Hyderabad,Hyper,Home Care,PepsiCo,Offline,Wallet,1,80.626759,...,25.407438,0.239616,130,24,5,26.0,F,1,October,Wednesday
2,23283831,2024-08-26 22:03:00,Chennai,Hyper,Snacks,PepsiCo,Online,Card,5,181.233170,...,138.734266,0.132773,270,44,8,27.0,F,0,August,Monday
3,53537460,2024-06-09 04:34:00,Bengaluru,Hyper,Beverages,Nestle,Omnichannel,Card,2,195.811403,...,130.137115,0.249420,403,63,8,NaN,F,0,June,Sunday
4,55348596,2024-06-07 01:13:00,Delhi,Super,Snacks,ITC,Offline,Card,3,23.571888,...,21.157751,0.230292,366,40,9,60.0,F,1,June,Friday
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,51439182,2024-08-11 14:58:00,Mumbai,Express,Dairy,Britannia,Online,Cash,5,128.336814,...,226.955069,0.261277,70,76,6,25.0,NaN,0,August,Sunday
99996,76433622,2024-11-27 11:02:00,Ahmedabad,Express,Dairy,Amul,Offline,Wallet,4,183.100266,...,229.419198,0.238526,482,31,14,25.0,M,1,November,Wednesday
99997,80228351,2024-02-21 09:25:00,Bengaluru,Express,Beverages,ITC,Omnichannel,Wallet,2,163.630389,...,22.679513,0.064810,411,40,4,NaN,F,0,February,Wednesday
99998,49574701,2024-03-30 04:11:00,Chennai,Hyper,Dairy,PepsiCo,Offline,UPI,4,50.230907,...,69.208946,0.256204,488,46,12,21.0,M,1,March,Saturday
99999,17631041,2024-07-11 08:42:00,Pune,Super,Snacks,ITC,Offline,UPI,2,14.754033,...,8.666590,0.227025,211,22,9,26.0,M,0,July,Thursday

In [15]:
# Handling Missing Customer_Age Column

df['Customer_Age'] = df['Customer_Age'].fillna(df['Customer_Age'].median())
df

,Invoice_ID,Invoice_Date,City,Store_Format,Category,Brand,Channel,Payment_Mode,Units,Cost_Price,...,Margin,Margin_%,Stock_On_Hand,Reorder_Level,Lead_Time_Days,Customer_Age,Customer_Gender,Loyalty_Flag,Month,Day
0,58018430,2024-02-02 13:50:00,Kolkata,Super,Grocery,Nestle,Online,Wallet,2,148.999035,...,52.116348,0.148855,154,31,11,20.0,M,1,February,Friday
1,48157952,2024-10-09 11:52:00,Hyderabad,Hyper,Home Care,PepsiCo,Offline,Wallet,1,80.626759,...,25.407438,0.239616,130,24,5,26.0,F,1,October,Wednesday
2,23283831,2024-08-26 22:03:00,Chennai,Hyper,Snacks,PepsiCo,Online,Card,5,181.233170,...,138.734266,0.132773,270,44,8,27.0,F,0,August,Monday
3,53537460,2024-06-09 04:34:00,Bengaluru,Hyper,Beverages,Nestle,Omnichannel,Card,2,195.811403,...,130.137115,0.249420,403,63,8,41.0,F,0,June,Sunday
4,55348596,2024-06-07 01:13:00,Delhi,Super,Snacks,ITC,Offline,Card,3,23.571888,...,21.157751,0.230292,366,40,9,60.0,F,1,June,Friday
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,51439182,2024-08-11 14:58:00,Mumbai,Express,Dairy,Britannia,Online,Cash,5,128.336814,...,226.955069,0.261277,70,76,6,25.0,NaN,0,August,Sunday
99996,76433622,2024-11-27 11:02:00,Ahmedabad,Express,Dairy,Amul,Offline,Wallet,4,183.100266,...,229.419198,0.238526,482,31,14,25.0,M,1,November,Wednesday
99997,80228351,2024-02-21 09:25:00,Bengaluru,Express,Beverages,ITC,Omnichannel,Wallet,2,163.630389,...,22.679513,0.064810,411,40,4,41.0,F,0,February,Wednesday
99998,49574701,2024-03-30 04:11:00,Chennai,Hyper,Dairy,PepsiCo,Offline,UPI,4,50.230907,...,69.208946,0.256204,488,46,12,21.0,M,1,March,Saturday
99999,17631041,2024-07-11 08:42:00,Pune,Super,Snacks,ITC,Offline,UPI,2,14.754033,...,8.666590,0.227025,211,22,9,26.0,M,0,July,Thursday

In [16]:
# Handling Customer_Gender Column

df['Customer_Gender'] = df['Customer_Gender'].fillna('Unknown')
df

,Invoice_ID,Invoice_Date,City,Store_Format,Category,Brand,Channel,Payment_Mode,Units,Cost_Price,...,Margin,Margin_%,Stock_On_Hand,Reorder_Level,Lead_Time_Days,Customer_Age,Customer_Gender,Loyalty_Flag,Month,Day
0,58018430,2024-02-02 13:50:00,Kolkata,Super,Grocery,Nestle,Online,Wallet,2,148.999035,...,52.116348,0.148855,154,31,11,20.0,M,1,February,Friday
1,48157952,2024-10-09 11:52:00,Hyderabad,Hyper,Home Care,PepsiCo,Offline,Wallet,1,80.626759,...,25.407438,0.239616,130,24,5,26.0,F,1,October,Wednesday
2,23283831,2024-08-26 22:03:00,Chennai,Hyper,Snacks,PepsiCo,Online,Card,5,181.233170,...,138.734266,0.132773,270,44,8,27.0,F,0,August,Monday
3,53537460,2024-06-09 04:34:00,Bengaluru,Hyper,Beverages,Nestle,Omnichannel,Card,2,195.811403,...,130.137115,0.249420,403,63,8,41.0,F,0,June,Sunday
4,55348596,2024-06-07 01:13:00,Delhi,Super,Snacks,ITC,Offline,Card,3,23.571888,...,21.157751,0.230292,366,40,9,60.0,F,1,June,Friday
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,51439182,2024-08-11 14:58:00,Mumbai,Express,Dairy,Britannia,Online,Cash,5,128.336814,...,226.955069,0.261277,70,76,6,25.0,Unknown,0,August,Sunday
99996,76433622,2024-11-27 11:02:00,Ahmedabad,Express,Dairy,Amul,Offline,Wallet,4,183.100266,...,229.419198,0.238526,482,31,14,25.0,M,1,November,Wednesday
99997,80228351,2024-02-21 09:25:00,Bengaluru,Express,Beverages,ITC,Omnichannel,Wallet,2,163.630389,...,22.679513,0.064810,411,40,4,41.0,F,0,February,Wednesday
99998,49574701,2024-03-30 04:11:00,Chennai,Hyper,Dairy,PepsiCo,Offline,UPI,4,50.230907,...,69.208946,0.256204,488,46,12,21.0,M,1,March,Saturday
99999,17631041,2024-07-11 08:42:00,Pune,Super,Snacks,ITC,Offline,UPI,2,14.754033,...,8.666590,0.227025,211,22,9,26.0,M,0,July,Thursday

In [17]:
df.drop_duplicates()
df

,Invoice_ID,Invoice_Date,City,Store_Format,Category,Brand,Channel,Payment_Mode,Units,Cost_Price,...,Margin,Margin_%,Stock_On_Hand,Reorder_Level,Lead_Time_Days,Customer_Age,Customer_Gender,Loyalty_Flag,Month,Day
0,58018430,2024-02-02 13:50:00,Kolkata,Super,Grocery,Nestle,Online,Wallet,2,148.999035,...,52.116348,0.148855,154,31,11,20.0,M,1,February,Friday
1,48157952,2024-10-09 11:52:00,Hyderabad,Hyper,Home Care,PepsiCo,Offline,Wallet,1,80.626759,...,25.407438,0.239616,130,24,5,26.0,F,1,October,Wednesday
2,23283831,2024-08-26 22:03:00,Chennai,Hyper,Snacks,PepsiCo,Online,Card,5,181.233170,...,138.734266,0.132773,270,44,8,27.0,F,0,August,Monday
3,53537460,2024-06-09 04:34:00,Bengaluru,Hyper,Beverages,Nestle,Omnichannel,Card,2,195.811403,...,130.137115,0.249420,403,63,8,41.0,F,0,June,Sunday
4,55348596,2024-06-07 01:13:00,Delhi,Super,Snacks,ITC,Offline,Card,3,23.571888,...,21.157751,0.230292,366,40,9,60.0,F,1,June,Friday
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,51439182,2024-08-11 14:58:00,Mumbai,Express,Dairy,Britannia,Online,Cash,5,128.336814,...,226.955069,0.261277,70,76,6,25.0,Unknown,0,August,Sunday
99996,76433622,2024-11-27 11:02:00,Ahmedabad,Express,Dairy,Amul,Offline,Wallet,4,183.100266,...,229.419198,0.238526,482,31,14,25.0,M,1,November,Wednesday
99997,80228351,2024-02-21 09:25:00,Bengaluru,Express,Beverages,ITC,Omnichannel,Wallet,2,163.630389,...,22.679513,0.064810,411,40,4,41.0,F,0,February,Wednesday
99998,49574701,2024-03-30 04:11:00,Chennai,Hyper,Dairy,PepsiCo,Offline,UPI,4,50.230907,...,69.208946,0.256204,488,46,12,21.0,M,1,March,Saturday
99999,17631041,2024-07-11 08:42:00,Pune,Super,Snacks,ITC,Offline,UPI,2,14.754033,...,8.666590,0.227025,211,22,9,26.0,M,0,July,Thursday

In [18]:
df['Customer_Gender'] = df['Customer_Gender'].replace('M', 'Male')
df['Customer_Gender'] = df['Customer_Gender'].replace('F', 'Female')
df['Customer_Gender'] = df['Customer_Gender'].replace('O', 'Other')
df

,Invoice_ID,Invoice_Date,City,Store_Format,Category,Brand,Channel,Payment_Mode,Units,Cost_Price,...,Margin,Margin_%,Stock_On_Hand,Reorder_Level,Lead_Time_Days,Customer_Age,Customer_Gender,Loyalty_Flag,Month,Day
0,58018430,2024-02-02 13:50:00,Kolkata,Super,Grocery,Nestle,Online,Wallet,2,148.999035,...,52.116348,0.148855,154,31,11,20.0,Male,1,February,Friday
1,48157952,2024-10-09 11:52:00,Hyderabad,Hyper,Home Care,PepsiCo,Offline,Wallet,1,80.626759,...,25.407438,0.239616,130,24,5,26.0,Female,1,October,Wednesday
2,23283831,2024-08-26 22:03:00,Chennai,Hyper,Snacks,PepsiCo,Online,Card,5,181.233170,...,138.734266,0.132773,270,44,8,27.0,Female,0,August,Monday
3,53537460,2024-06-09 04:34:00,Bengaluru,Hyper,Beverages,Nestle,Omnichannel,Card,2,195.811403,...,130.137115,0.249420,403,63,8,41.0,Female,0,June,Sunday
4,55348596,2024-06-07 01:13:00,Delhi,Super,Snacks,ITC,Offline,Card,3,23.571888,...,21.157751,0.230292,366,40,9,60.0,Female,1,June,Friday
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,51439182,2024-08-11 14:58:00,Mumbai,Express,Dairy,Britannia,Online,Cash,5,128.336814,...,226.955069,0.261277,70,76,6,25.0,Unknown,0,August,Sunday
99996,76433622,2024-11-27 11:02:00,Ahmedabad,Express,Dairy,Amul,Offline,Wallet,4,183.100266,...,229.419198,0.238526,482,31,14,25.0,Male,1,November,Wednesday
99997,80228351,2024-02-21 09:25:00,Bengaluru,Express,Beverages,ITC,Omnichannel,Wallet,2,163.630389,...,22.679513,0.064810,411,40,4,41.0,Female,0,February,Wednesday
99998,49574701,2024-03-30 04:11:00,Chennai,Hyper,Dairy,PepsiCo,Offline,UPI,4,50.230907,...,69.208946,0.256204,488,46,12,21.0,Male,1,March,Saturday
99999,17631041,2024-07-11 08:42:00,Pune,Super,Snacks,ITC,Offline,UPI,2,14.754033,...,8.666590,0.227025,211,22,9,26.0,Male,0,July,Thursday

In [19]:
# Data Validation
# Revenue Validation

df['Calculated_Revenue'] = df['Units'] * df['Selling_Price']
df

,Invoice_ID,Invoice_Date,City,Store_Format,Category,Brand,Channel,Payment_Mode,Units,Cost_Price,...,Margin_%,Stock_On_Hand,Reorder_Level,Lead_Time_Days,Customer_Age,Customer_Gender,Loyalty_Flag,Month,Day,Calculated_Revenue
0,58018430,2024-02-02 13:50:00,Kolkata,Super,Grocery,Nestle,Online,Wallet,2,148.999035,...,0.148855,154,31,11,20.0,Male,1,February,Friday,350.114418
1,48157952,2024-10-09 11:52:00,Hyderabad,Hyper,Home Care,PepsiCo,Offline,Wallet,1,80.626759,...,0.239616,130,24,5,26.0,Female,1,October,Wednesday,106.034197
2,23283831,2024-08-26 22:03:00,Chennai,Hyper,Snacks,PepsiCo,Online,Card,5,181.233170,...,0.132773,270,44,8,27.0,Female,0,August,Monday,1044.900114
3,53537460,2024-06-09 04:34:00,Bengaluru,Hyper,Beverages,Nestle,Omnichannel,Card,2,195.811403,...,0.249420,403,63,8,41.0,Female,0,June,Sunday,521.759920
4,55348596,2024-06-07 01:13:00,Delhi,Super,Snacks,ITC,Offline,Card,3,23.571888,...,0.230292,366,40,9,60.0,Female,1,June,Friday,91.873416
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,51439182,2024-08-11 14:58:00,Mumbai,Express,Dairy,Britannia,Online,Cash,5,128.336814,...,0.261277,70,76,6,25.0,Unknown,0,August,Sunday,868.639139
99996,76433622,2024-11-27 11:02:00,Ahmedabad,Express,Dairy,Amul,Offline,Wallet,4,183.100266,...,0.238526,482,31,14,25.0,Male,1,November,Wednesday,961.820263
99997,80228351,2024-02-21 09:25:00,Bengaluru,Express,Beverages,ITC,Omnichannel,Wallet,2,163.630389,...,0.064810,411,40,4,41.0,Female,0,February,Wednesday,349.940290
99998,49574701,2024-03-30 04:11:00,Chennai,Hyper,Dairy,PepsiCo,Offline,UPI,4,50.230907,...,0.256204,488,46,12,21.0,Male,1,March,Saturday,270.132573
99999,17631041,2024-07-11 08:42:00,Pune,Super,Snacks,ITC,Offline,UPI,2,14.754033,...,0.227025,211,22,9,26.0,Male,0,July,Thursday,38.174656

In [20]:
# Cost Validation

df['Calculated_Cost'] = df['Units'] * df['Cost_Price']
df

,Invoice_ID,Invoice_Date,City,Store_Format,Category,Brand,Channel,Payment_Mode,Units,Cost_Price,...,Stock_On_Hand,Reorder_Level,Lead_Time_Days,Customer_Age,Customer_Gender,Loyalty_Flag,Month,Day,Calculated_Revenue,Calculated_Cost
0,58018430,2024-02-02 13:50:00,Kolkata,Super,Grocery,Nestle,Online,Wallet,2,148.999035,...,154,31,11,20.0,Male,1,February,Friday,350.114418,297.998070
1,48157952,2024-10-09 11:52:00,Hyderabad,Hyper,Home Care,PepsiCo,Offline,Wallet,1,80.626759,...,130,24,5,26.0,Female,1,October,Wednesday,106.034197,80.626759
2,23283831,2024-08-26 22:03:00,Chennai,Hyper,Snacks,PepsiCo,Online,Card,5,181.233170,...,270,44,8,27.0,Female,0,August,Monday,1044.900114,906.165848
3,53537460,2024-06-09 04:34:00,Bengaluru,Hyper,Beverages,Nestle,Omnichannel,Card,2,195.811403,...,403,63,8,41.0,Female,0,June,Sunday,521.759920,391.622805
4,55348596,2024-06-07 01:13:00,Delhi,Super,Snacks,ITC,Offline,Card,3,23.571888,...,366,40,9,60.0,Female,1,June,Friday,91.873416,70.715665
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,51439182,2024-08-11 14:58:00,Mumbai,Express,Dairy,Britannia,Online,Cash,5,128.336814,...,70,76,6,25.0,Unknown,0,August,Sunday,868.639139,641.684070
99996,76433622,2024-11-27 11:02:00,Ahmedabad,Express,Dairy,Amul,Offline,Wallet,4,183.100266,...,482,31,14,25.0,Male,1,November,Wednesday,961.820263,732.401065
99997,80228351,2024-02-21 09:25:00,Bengaluru,Express,Beverages,ITC,Omnichannel,Wallet,2,163.630389,...,411,40,4,41.0,Female,0,February,Wednesday,349.940290,327.260777
99998,49574701,2024-03-30 04:11:00,Chennai,Hyper,Dairy,PepsiCo,Offline,UPI,4,50.230907,...,488,46,12,21.0,Male,1,March,Saturday,270.132573,200.923627
99999,17631041,2024-07-11 08:42:00,Pune,Super,Snacks,ITC,Offline,UPI,2,14.754033,...,211,22,9,26.0,Male,0,July,Thursday,38.174656,29.508066

In [21]:
# MArgin Validation

df['Calculated_Margin'] = df['Calculated_Revenue'] - df['Calculated_Cost']
df

,Invoice_ID,Invoice_Date,City,Store_Format,Category,Brand,Channel,Payment_Mode,Units,Cost_Price,...,Reorder_Level,Lead_Time_Days,Customer_Age,Customer_Gender,Loyalty_Flag,Month,Day,Calculated_Revenue,Calculated_Cost,Calculated_Margin
0,58018430,2024-02-02 13:50:00,Kolkata,Super,Grocery,Nestle,Online,Wallet,2,148.999035,...,31,11,20.0,Male,1,February,Friday,350.114418,297.998070,52.116348
1,48157952,2024-10-09 11:52:00,Hyderabad,Hyper,Home Care,PepsiCo,Offline,Wallet,1,80.626759,...,24,5,26.0,Female,1,October,Wednesday,106.034197,80.626759,25.407438
2,23283831,2024-08-26 22:03:00,Chennai,Hyper,Snacks,PepsiCo,Online,Card,5,181.233170,...,44,8,27.0,Female,0,August,Monday,1044.900114,906.165848,138.734266
3,53537460,2024-06-09 04:34:00,Bengaluru,Hyper,Beverages,Nestle,Omnichannel,Card,2,195.811403,...,63,8,41.0,Female,0,June,Sunday,521.759920,391.622805,130.137115
4,55348596,2024-06-07 01:13:00,Delhi,Super,Snacks,ITC,Offline,Card,3,23.571888,...,40,9,60.0,Female,1,June,Friday,91.873416,70.715665,21.157751
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,51439182,2024-08-11 14:58:00,Mumbai,Express,Dairy,Britannia,Online,Cash,5,128.336814,...,76,6,25.0,Unknown,0,August,Sunday,868.639139,641.684070,226.955069
99996,76433622,2024-11-27 11:02:00,Ahmedabad,Express,Dairy,Amul,Offline,Wallet,4,183.100266,...,31,14,25.0,Male,1,November,Wednesday,961.820263,732.401065,229.419198
99997,80228351,2024-02-21 09:25:00,Bengaluru,Express,Beverages,ITC,Omnichannel,Wallet,2,163.630389,...,40,4,41.0,Female,0,February,Wednesday,349.940290,327.260777,22.679513
99998,49574701,2024-03-30 04:11:00,Chennai,Hyper,Dairy,PepsiCo,Offline,UPI,4,50.230907,...,46,12,21.0,Male,1,March,Saturday,270.132573,200.923627,69.208946
99999,17631041,2024-07-11 08:42:00,Pune,Super,Snacks,ITC,Offline,UPI,2,14.754033,...,22,9,26.0,Male,0,July,Thursday,38.174656,29.508066,8.666590

In [22]:
# Saving the Cleaned FMCG DataSet

df.to_csv('FMCG Cleaned Dataset.csv', index = False)
df

,Invoice_ID,Invoice_Date,City,Store_Format,Category,Brand,Channel,Payment_Mode,Units,Cost_Price,...,Reorder_Level,Lead_Time_Days,Customer_Age,Customer_Gender,Loyalty_Flag,Month,Day,Calculated_Revenue,Calculated_Cost,Calculated_Margin
0,58018430,2024-02-02 13:50:00,Kolkata,Super,Grocery,Nestle,Online,Wallet,2,148.999035,...,31,11,20.0,Male,1,February,Friday,350.114418,297.998070,52.116348
1,48157952,2024-10-09 11:52:00,Hyderabad,Hyper,Home Care,PepsiCo,Offline,Wallet,1,80.626759,...,24,5,26.0,Female,1,October,Wednesday,106.034197,80.626759,25.407438
2,23283831,2024-08-26 22:03:00,Chennai,Hyper,Snacks,PepsiCo,Online,Card,5,181.233170,...,44,8,27.0,Female,0,August,Monday,1044.900114,906.165848,138.734266
3,53537460,2024-06-09 04:34:00,Bengaluru,Hyper,Beverages,Nestle,Omnichannel,Card,2,195.811403,...,63,8,41.0,Female,0,June,Sunday,521.759920,391.622805,130.137115
4,55348596,2024-06-07 01:13:00,Delhi,Super,Snacks,ITC,Offline,Card,3,23.571888,...,40,9,60.0,Female,1,June,Friday,91.873416,70.715665,21.157751
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,51439182,2024-08-11 14:58:00,Mumbai,Express,Dairy,Britannia,Online,Cash,5,128.336814,...,76,6,25.0,Unknown,0,August,Sunday,868.639139,641.684070,226.955069
99996,76433622,2024-11-27 11:02:00,Ahmedabad,Express,Dairy,Amul,Offline,Wallet,4,183.100266,...,31,14,25.0,Male,1,November,Wednesday,961.820263,732.401065,229.419198
99997,80228351,2024-02-21 09:25:00,Bengaluru,Express,Beverages,ITC,Omnichannel,Wallet,2,163.630389,...,40,4,41.0,Female,0,February,Wednesday,349.940290,327.260777,22.679513
99998,49574701,2024-03-30 04:11:00,Chennai,Hyper,Dairy,PepsiCo,Offline,UPI,4,50.230907,...,46,12,21.0,Male,1,March,Saturday,270.132573,200.923627,69.208946
99999,17631041,2024-07-11 08:42:00,Pune,Super,Snacks,ITC,Offline,UPI,2,14.754033,...,22,9,26.0,Male,0,July,Thursday,38.174656,29.508066,8.666590